// Single source of truth for tier details across the app.
// Referenced by the pricing page, profile billing, FAQ, AI chatbot,
// upgrade modals, and tutorials. All other files should import from here
// rather than redefining tier names, prices, or limits.
//
// For programmatic limit enforcement (server-side gates that need real
// numbers not the "unlimited" string), see the numeric helpers at the bottom
// of this file.

// Project seats are a standalone add-on, not included in any tier.
export const TIERS = {
  postcard: {
    name: "Postcard",
    tagline: "Try it free",
    monthlyPrice: 0,
    yearlyPrice: 0,
    oneTimePrice: null,
    limits: {
      activeEvents: 1,
      guestsPerEvent: 75,
      aiGenerations: 0,
      smsRemindersPerEvent: 0,
      // Email invitations are included on every plan, Postcard included
      // (2026-08-21). The send path in events-invites.functions.ts has no
      // tier gate — keep these in sync.
      emailInvitations: true,
      photoWall: false,
      seatingChart: false,
      exports: false,
      vendorRfq: false,
      checkIn: false,
      announcements: "in-app only",
      branding: false,
      guestImport: false,
      thankYouCards: false,
      plusOneLimit: true,
      eventCapacity: true,
      waitlist: false,
      rsvpDeadline: true,
    },
    features: [
      "1 event",
      "75 guests",
      "Shareable invite link",
      "Email invitations",
      "RSVP tracking",
      "Basic event page",
      "Potluck sign-up sheet",
      "Guest search & filters",
      "Plus-one controls",
      "Event capacity cap",
      "RSVP deadline",
    ],
    notIncluded: [
      "AI features",
      "Photo Wall",
      "Seating charts",
      "Exports",
      "SMS reminders",
      "Waitlist",
    ],
  },
  whisper: {
    name: "Whisper",
    tagline: "For a single gathering",
    monthlyPrice: 5,
    yearlyPrice: 39,
    oneTimePrice: 7,
    limits: {
      activeEvents: 3,
      guestsPerEvent: 150,
      aiGenerations: 0,
      smsRemindersPerEvent: 0,
      emailInvitations: true,
      photoWall: false,
      seatingChart: false,
      exports: "basic",
      vendorRfq: false,
      checkIn: false,
      announcements: "email + SMS + in-app",
      branding: false,
      guestImport: false,
      thankYouCards: false,
      plusOneLimit: true,
      eventCapacity: true,
      waitlist: true,
      rsvpDeadline: true,
    },
    features: [
      "3 active events",
      "150 guests per event",
      "Email invitations",
      "Free AI art for your Vibe gallery",
      "Basic exports (PDF)",
      "Plus-one controls",
      "Event capacity cap",
      "Waitlist",
      "RSVP deadline",
      "1 co-host or viewer seat",
      "Potluck sign-up sheet",
      "Guest search & filters",
    ],
    notIncluded: [
      "AI features",
      "SMS reminders",
      "Photo Wall",
      "Guest import",
      "Seating charts",
      "Check-in",
      "Vendor marketplace",
      "Custom branding",
    ],
  },
  host: {
    name: "Host",
    tagline: "For the frequent entertainer",
    monthlyPrice: 12,
    yearlyPrice: 99,
    oneTimePrice: 49,
    limits: {
      activeEvents: 10,
      guestsPerEvent: 750,
      aiGenerations: 0,
      smsRemindersPerEvent: 50,
      emailInvitations: true,
      photoWall: false,
      seatingChart: false,
      exports: "all",
      vendorRfq: true,
      checkIn: false,
      announcements: "email + SMS + in-app",
      branding: true,
      guestImport: false,
      thankYouCards: false,
      plusOneLimit: true,
      eventCapacity: true,
      waitlist: true,
      rsvpDeadline: true,
    },
    features: [
      "Everything in Whisper",
      "10 active events",
      "750 guests per event",
      "Vendor marketplace",
      "Custom branding",
      "50 SMS reminders",
      "All exports",
      "2 co-host or viewer seats",
      "T-shirt sizes with priced shirt line items",
      "Per-guest payment tracking & reconciliation",
    ],
    notIncluded: ["AI design features", "Seating charts", "Check-in", "Run of show"],
  },
  atelier: {
    name: "Atelier",
    tagline: "The full creative suite",
    monthlyPrice: 29,
    yearlyPrice: 249,
    oneTimePrice: 99,
    oneTimeAiCap: 150,
    limits: {
      activeEvents: "unlimited",
      guestsPerEvent: "unlimited",
      aiGenerations: "unlimited",
      smsRemindersPerEvent: "unlimited",
      emailInvitations: true,
      photoWall: true,
      seatingChart: true,
      exports: "all",
      vendorRfq: true,
      checkIn: true,
      announcements: "email + SMS + in-app",
      branding: true,
      guestImport: true,
      thankYouCards: true,
      plusOneLimit: true,
      eventCapacity: true,
      waitlist: true,
      rsvpDeadline: true,
    },
    features: [
      "Everything in Host",
      "Unlimited events",
      "Unlimited guests",
      "Guest import",
      "Contacts CRM (cross-event address book)",
      "Thank-you cards studio",
      "Seating charts",
      "Door check-in with walk-in guests",
      "Run of show",
      "5 co-host or viewer seats",
      "AI design studio",
      "Unlimited SMS",
      "Priority everything",
    ],
    notIncluded: [],
  },
} as const;

export type TierKey = keyof typeof TIERS;
export type Tier = (typeof TIERS)[TierKey];

// ---------------------------------------------------------------------------
// Numeric limit helpers — re-exported from tier-limits.ts, which is the
// single source of truth for programmatic enforcement. Import from here
// when you also need TIERS (copy/features); import from tier-limits directly
// when you only need the numbers.
// ---------------------------------------------------------------------------
export {
  TIER_LIMITS,
  PM_ADDON_SEAT_LIMITS,
  isUnlimited,
  getTierLimits,
  getEffectiveProjectSeats,
  getEffectiveSmsCap,
  canSendSms,
  SMS_PACK_PRICE_ID,
  SMS_PACK_PER_EVENT_ALLOWANCE,
} from "@/lib/tier-limits";
export type { TierLimits } from "@/lib/tier-limits";
