import { useEffect, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useRouterState } from "@tanstack/react-router";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { supportChat } from "@/lib/support.functions";
import { Sparkles, X } from "lucide-react";

/**
 * Floating ✨ button: click for a plain-English summary of the current page
 * and recommended next action, generated by the Concierge.
 */
export function ExplainPageButton() {
  const ask = useServerFn(supportChat);
  const path = useRouterState({ select: (r) => r.location.pathname });
  const [open, setOpen] = useState(false);
  const [reply, setReply] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  // Reset the cached explanation whenever the user navigates to a new page —
  // otherwise the modal shows the previous page's summary verbatim.
  useEffect(() => {
    setReply(null);
    setLoading(false);
    setOpen(false);
  }, [path]);

  // Hide on auth / not-found shells where it has no value.
  if (path.startsWith("/auth") || path === "/404") return null;

  async function explain() {
    setOpen(true);
    if (reply || loading) return;
    setLoading(true);
    try {
      // Gather lightweight page context so the Concierge doesn't have to guess.
      let title = "";
      let h1 = "";
      let h2s: string[] = [];
      if (typeof document !== "undefined") {
        title = document.title || "";
        h1 = document.querySelector("h1")?.textContent?.trim().slice(0, 160) ?? "";
        h2s = Array.from(document.querySelectorAll("h2, h3"))
          .slice(0, 8)
          .map((n) => n.textContent?.trim() ?? "")
          .filter(Boolean)
          .map((s) => s.slice(0, 100));
      }
      const ctx = [
        `Route path: ${path}`,
        title && `Document title: ${title}`,
        h1 && `Main heading: ${h1}`,
        h2s.length > 0 && `Section headings: ${h2s.join(" • ")}`,
      ].filter(Boolean).join("\n");

      const r = await ask({
        data: {
          messages: [{
            role: "user",
            content:
              `I'm currently viewing this specific page in The Kenroe Collective app. ` +
              `Using the context below, explain in 4–6 short sentences what THIS page is for, ` +
              `what I can do here, and the single most valuable next action. ` +
              `Tailor the answer to this exact route — do not give a generic app overview. ` +
              `Plain English, no greetings, no jargon.\n\n${ctx}`,
          }],
        },
      });
      setReply(r.reply);
    } catch {
      setReply("I couldn't reach the Concierge — try again in a moment.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <button
        type="button"
        onClick={explain}
        aria-label="Explain this page"
        title="Explain this page"
        className="fixed bottom-5 right-24 z-40 hidden h-10 items-center gap-1.5 rounded-full bg-paper px-3 text-xs font-medium text-velvet shadow-lg ring-1 ring-velvet/20 hover:bg-secondary md:inline-flex"
      >
        <Sparkles className="h-3.5 w-3.5" /> Explain this page
      </button>

      {open && (
        <div className="fixed inset-0 z-50 flex items-end justify-end p-5 sm:items-center sm:justify-center">
          <button
            aria-label="Close"
            onClick={() => setOpen(false)}
            className="absolute inset-0 bg-black/40"
          />
          <div className="relative z-10 w-full max-w-md overflow-hidden rounded-3xl bg-paper shadow-2xl ring-1 ring-ink/10">
            <div className="flex items-center justify-between border-b border-ink/5 bg-ink px-4 py-3 text-paper">
              <div className="flex items-center gap-2">
                <Sparkles className="h-4 w-4" />
                <span className="font-serif text-sm">About this page</span>
              </div>
              <button onClick={() => setOpen(false)} aria-label="Close" className="rounded-full p-1 hover:bg-paper/10">
                <X className="h-4 w-4" />
              </button>
            </div>
            <div className="max-h-[60vh] overflow-y-auto p-5 text-sm leading-6 text-ink">
              {loading && <p className="text-muted-foreground">Reading the page…</p>}
              {reply && (
                <div className="prose prose-sm max-w-none [&_p]:my-2 [&_ul]:my-2 [&_ul]:list-disc [&_ul]:pl-4">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{reply}</ReactMarkdown>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}
