import React from "react";
import { AbsoluteFill, Audio, Img, Sequence, Video, staticFile, useCurrentFrame, useVideoConfig, interpolate } from "remotion";
import type { Cut, FilmData, Scene } from "./data";
import { DISCLOSURE } from "./data";

const ink="#f8f3ea", oxblood="#4e211e", dark="#17120f", gold="#a98e66";
function Device({children,vertical}:{children:React.ReactNode;vertical:boolean}) { return <AbsoluteFill style={{background:"radial-gradient(circle at 50% 35%,#4e211e 0,#211715 55%,#120e0d 100%)",alignItems:"center",justifyContent:"center"}}><div style={{position:"relative",height:vertical?"72%":"91%",aspectRatio:"390 / 844",border:"10px solid #2b2420",borderRadius:vertical?52:36,overflow:"hidden",boxShadow:"0 30px 90px #000",background:"white"}}>{children}</div></AbsoluteFill> }
function EndCard({film,cut}:{film:FilmData;cut:Cut}) { const vertical=cut==="vertical", frame=useCurrentFrame(); const opacity=interpolate(frame,[0,12],[0,1],{extrapolateRight:"clamp"}); return <AbsoluteFill style={{background:ink,color:oxblood,alignItems:"center",justifyContent:"center",textAlign:"center",padding:vertical?"300px 80px 400px":"100px"}}><div style={{opacity}}><div style={{fontFamily:"Georgia,serif",fontSize:vertical?92:86,lineHeight:1.05}}>{film.title}</div>{film.status?<div style={{marginTop:28,fontSize:vertical?42:32,textTransform:"uppercase"}}>{film.status}</div>:null}<div style={{marginTop:44,fontSize:vertical?34:27}}>{film.actions.join(" | ")}</div><div style={{marginTop:64,fontSize:vertical?25:19,color:"#5f5a54"}}>{DISCLOSURE}</div></div></AbsoluteFill> }
function SceneView({scene,cut,filmKey}:{scene:Scene;cut:Cut;filmKey:string}) { const vertical=cut==="vertical"; const frameNow=useCurrentFrame(); const {durationInFrames,fps}=useVideoConfig(); if(!scene.file&&!scene.image&&!scene.verticalCardImage) return null;
  const cardImage=vertical&&scene.verticalCardImage?scene.verticalCardImage:scene.image; const zoom=interpolate(frameNow,[0,Math.max(durationInFrames,1)],[1,1.05],{extrapolateRight:"clamp"}); let base:React.ReactNode; if(cardImage&&scene.card){ base=<AbsoluteFill style={{background:"radial-gradient(circle at 50% 35%,#4e211e 0,#211715 55%,#120e0d 100%)",alignItems:"center",justifyContent:"center",overflow:"hidden"}}><Img src={staticFile(vertical&&scene.card.verticalImage?scene.card.verticalImage:cardImage)} style={{width:vertical?scene.card.verticalWidth:scene.card.width,height:"auto",transform:`scale(${zoom})`,borderRadius:30,boxShadow:"0 30px 90px rgba(0,0,0,.55)"}}/>{scene.label?<div style={{position:"absolute",left:vertical?80:100,right:vertical?80:100,top:vertical?290:60,color:ink,background:"#4e211e",border:`1px solid ${gold}`,padding:"16px 22px",fontSize:vertical?35:27,textAlign:"center",borderRadius:12}}>{scene.label}</div>:null}</AbsoluteFill>; } else { const usePortrait=vertical&&!!scene.portraitFile; const file=usePortrait?scene.portraitFile:scene.file; const startAt=usePortrait&&scene.portraitFrom!==undefined?scene.portraitFrom:(scene.from??0); const crop=scene.crop?.[cut]; const frameStyle:React.CSSProperties=crop?{position:"absolute",width:`${crop.scale*100}%`,height:`${crop.scale*100}%`,left:`${(1-crop.scale)*crop.x}%`,top:`${(1-crop.scale)*crop.y}%`}:{position:"absolute",inset:0}; const mediaStyle:React.CSSProperties={width:"100%",height:"100%",objectFit:scene.fit??"cover",objectPosition:crop&&crop.scale===1?`${crop.x}% ${crop.y}%`:"center"}; const media=<div style={frameStyle}>{scene.image?<Img src={staticFile(scene.image)} style={mediaStyle}/>:<Video src={staticFile(`footage/${file}`)} startFrom={Math.round(startAt*fps)} muted style={mediaStyle}/>}</div>; const phone=filmKey==="celebrations"&&(file?.includes("invite")||file?.includes("example")||file?.includes("ecard")); base=<AbsoluteFill style={{background:"radial-gradient(circle at 50% 35%,#4e211e 0,#211715 55%,#120e0d 100%)",overflow:"hidden"}}>{phone?<Device vertical={vertical}>{media}</Device>:media}{scene.label&&!(vertical&&scene.hideLabelVertical)?<div style={{position:"absolute",left:vertical?80:100,right:vertical?80:100,top:vertical?290:60,color:ink,background:"#4e211e",border:`1px solid ${gold}`,padding:"16px 22px",fontSize:vertical?35:27,textAlign:"center",borderRadius:12}}>{scene.label}</div>:null}</AbsoluteFill>; }
  if(!scene.leadImage) return base; const leadFrames=Math.max(Math.round((scene.leadImageSeconds??2)*fps),2); const fadeFrames=10; const baseOpacity=interpolate(frameNow,[leadFrames-fadeFrames,leadFrames],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}); const leadScale=interpolate(frameNow,[0,leadFrames],[1,1.025],{extrapolateRight:"clamp"}); return <AbsoluteFill style={{background:dark}}><Img src={staticFile(scene.leadImage)} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"contain",transform:`scale(${leadScale})`}}/><AbsoluteFill style={{opacity:baseOpacity}}>{base}</AbsoluteFill></AbsoluteFill> }
const voiceVolume=(frame:number,durationFrames:number,fps:number)=>{const fadeIn=Math.max(1,Math.round(.04*fps));const fadeOut=Math.max(1,Math.round(.15*fps));return Math.min(interpolate(frame,[0,fadeIn],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),interpolate(frame,[Math.max(fadeIn,durationFrames-fadeOut),durationFrames],[1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}));};
const bedVolume=(frame:number,film:FilmData,fps:number)=>{const time=frame/fps;const base=.075;const ducked=base*Math.pow(10,-6/20);const ramp=.25;let level=base;for(const line of film.lines){if(time>=line.start-ramp&&time<line.captionEnd+ramp){const down=interpolate(time,[line.start-ramp,line.start],[base,ducked],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});const up=interpolate(time,[line.captionEnd,line.captionEnd+ramp],[ducked,base],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});level=Math.min(level,down,up);}}const fadeIn=interpolate(time,[0,1],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});const endStart=film.lines.at(-1)?.start??Math.max(0,film.duration-2);const fadeOut=interpolate(time,[endStart,film.duration],[1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return level*fadeIn*fadeOut;};
export function Film({film,cut,hideCaptions=false}:{film:FilmData;cut:Cut;hideCaptions?:boolean}) { const frame=useCurrentFrame(),{fps}=useVideoConfig(),time=frame/fps,vertical=cut==="vertical"; const caption=film.lines.find(l=>time>=l.start&&time<l.captionEnd); const byId=new Map(film.lines.map(l=>[l.id,l])); const endCardActive=film.scenes.some((scene)=>{if(scene.file||scene.image)return false;const line=byId.get(scene.lineId);return line?time>=line.start&&time<line.sceneEnd+1.6:false}); const crossfadeFrames=film.smoothEditing?10:0; return <AbsoluteFill style={{background:dark,fontFamily:"Arial,sans-serif"}}>
  {film.scenes.map((scene,i)=>{const line=byId.get(scene.lineId); if(!line)return null; const visualStart=film.smoothEditing?(scene.start??Math.max(0,line.start-.2)):line.start; const nextScene=film.scenes[i+1]; const nextLine=nextScene?byId.get(nextScene.lineId):undefined; const nextStart=nextLine?(film.smoothEditing?(nextScene?.start??Math.max(0,nextLine.start-.2)):nextLine.start):undefined; const end=nextStart!==undefined?nextStart+crossfadeFrames/fps:line.sceneEnd+1.6; const from=Math.round(visualStart*fps); const duration=Math.max(1,Math.round((end-visualStart)*fps)); const fadeIn=film.smoothEditing&&i>0?interpolate(frame-from,[0,crossfadeFrames],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}):1; return <Sequence key={scene.lineId} from={from} durationInFrames={duration}><AbsoluteFill style={{opacity:fadeIn}}>{scene.file||scene.image?<SceneView scene={scene} cut={cut} filmKey={film.key}/>:<EndCard film={film} cut={cut}/>}</AbsoluteFill></Sequence>})}
  <Audio src={staticFile(`audio/${film.bed}`)} volume={film.smoothEditing?(audioFrame)=>bedVolume(audioFrame,film,fps):.075}/>
  {film.lines.map(line=>{const durationFrames=Math.ceil(line.duration*fps);return <Sequence key={line.id} from={Math.round(line.start*fps)}><Audio src={staticFile(`audio/${line.file}`)} volume={film.smoothEditing?(audioFrame)=>voiceVolume(audioFrame,durationFrames,fps):1}/></Sequence>})}
  {!hideCaptions&&caption&&!endCardActive?<div style={{position:"absolute",left:vertical?74:260,right:vertical?74:260,bottom:vertical?370:58,color:ink,background:"rgba(20,15,13,.91)",border:`1px solid ${gold}`,padding:vertical?"20px 24px":"14px 22px",fontSize:vertical?38:31,lineHeight:1.24,textAlign:"center",borderRadius:12}}>{caption.text}</div>:null}
 </AbsoluteFill> }